name: Request help fixing exe.xml file
description: This is the description
assignees:
  - RoystonS
body:
  - type: markdown
    attributes:
      value: |
        Use this form if you've tried to install BetterBravoLights but it refused to attempt
        to install because your MSFS `exe.xml` file was corrupt.

        However, rather than filling this form out manually, BetterBravoLights v0.3.1 and above
        comes with a one-click option that will populate this form for you automatically.

  - type: input
    id: version
    attributes:
      label: Software version
      description: Please indicate which version of BetterBravoLights you have
      placeholder: 0.7.0
    validations:
      required: true

  - type: dropdown
    id: installation-type
    attributes:
      label: Flight Simulator installation type
      options:
        - Windows Store
        - Steam
    validations:
      required: true
      
  - type: input
    id: exe_xml_path
    attributes:
      label: Location of my `exe.xml` file
      placeholder: C:\Users\myuser\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache
    validations:
      required: false
      
  - type: textarea
    id: exe_xml_contents
    attributes:
      label: Contents of my `exe.xml` file
      render: xml
      placeholder: |
        <?xml version="1.0" encoding="windows-1252"?>
        <Descr>Auto launch external applications on MSFS start</Descr>
        <Filename>exe.xml</Filename>
  
        </Launch.Addon>
         
         </SimBase.Document>
    validations:
      required: true
         
  - type: markdown
    attributes:
      value: |
        I understand that BetterBravoLights didn't corrupt the file and that it's simply warning
        about the corrupted file. But could you help me fix it?
